// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ReactQueryProvider from "@/components/ReactQueryProvider"; // ⬅️ new import

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <ReactQueryProvider>
          <nav className="fixed top-0 left-0 right-0 z-50 bg-black">
            <Navbar />
          </nav>
          <main className="mt-20">{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
