# Generated by Django 5.1 on 2025-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('sentiment_score', models.FloatField()),
                ('sentiment_category', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('Reddit', 'Reddit'), ('News', 'News')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
