# Generated by Django 5.1 on 2025-04-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysentiment',
            name='source',
        ),
        migrations.AddField(
            model_name='companysentiment',
            name='news_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysentiment',
            name='reddit_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companysentiment',
            name='sentiment_category',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=50),
        ),
    ]
