# Generated by Django 5.1 on 2025-04-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_companysentiment_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysentiment',
            name='stock_data',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
