# Generated by Django 5.1 on 2025-04-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companysentiment_stock_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('predicted_price', models.FloatField()),
                ('prediction_time', models.DateTimeField()),
            ],
        ),
    ]
