# Generated by Django 5.1 on 2025-04-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stockprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprediction',
            name='direction',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='predicted_percentage_change',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
