# Generated by Django 5.1 on 2025-04-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_stockprediction_direction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockprediction',
            old_name='predicted_price',
            new_name='predicted_price_with_sentiment',
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='avg_predicted_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='predicted_price_without_sentiment',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
