# Generated by Django 5.1 on 2025-04-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dailypoll_polloption_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailypoll',
            name='company',
        ),
        migrations.AddField(
            model_name='dailypoll',
            name='company_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
