# Generated by Django 5.1 on 2025-04-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_viewer_delete_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprediction',
            name='predicted_price_with_arima',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
