# Generated by Django 5.1 on 2025-04-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprediction',
            name='is_in',
            field=models.BooleanField(default=False),
        ),
    ]
